name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore CTU2Test.csproj

      - name: Build
        run: dotnet build CTU2Test.csproj --configuration Release --no-restore

      - name: Publish artifacts
        run: dotnet publish CTU2Test.csproj --configuration Release --output ./artifacts

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Specify your .NET version

      - name: Run unit tests
        run: dotnet test CTU2Test.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Publish code coverage results
        uses: codecov/codecov-action@v3
        with:
          file: 'coverage.cobertura.xml'

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment..."
          # Replace with your actual deployment commands
          # Example: ./deploy.sh staging
